name = "stakick-bot"
main = "src/index.js"
compatibility_date = "2026-08-08"
workers_dev = true

[vars]
BOT_USERNAME = "StakickBot"
OWNER_KICK_SLUG = "lakkygen"
OWNER_ID = "6816397800"
ENVIRONMENT = "production"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODEL = "poolside/laguna-xs-2.1:free"
BOT_TOKEN = "8897459739:AAFF6XZWwqSx4p1J5xeMMUhZiZHSx90p7BA"

[[kv_namespaces]]
binding = "KV"
id = "957dfd1492e34f07b00416e22110cacc"

[[d1_databases]]
binding = "DB"
database_name = "stakick-db"
database_id = "735e166d-dc36-4a19-8fdb-f0b33ef41f90"

[[migrations]]
tag = "delete-drop-alarm"
deleted_classes = ["DropAlarm"]

[triggers]
crons = ["* * * * *"]
